artifacts_root  = artifacts

data_ingestion:
  root_dir = artifacts.data_ingestion
  source_url = https://github.com/d-s-k-ai/Database-/blob/main/winequality-red.rar
  local_data_file = artifacts/data_ingestion/data.csv
  unzip_dir = artifacts/data_ingestion

